%该函数用于展示检测结果，更直观的展示请见GUI
orinimg=imread('test.tif');

figure(1)
tophatimg=tophat(orinimg);%血管形状方位图
imshow(tophatimg)
title('血管形状方位图')
figure(2)
climg=centerline(orinimg);%血管中心线
imshow(climg)
title('血管中心线')
figure(3)
[xf,yf]=find(climg==1);
tophatimg(find(tophatimg>0.3))=1;
tophatimg(find(tophatimg~=1))=0;
tophatimg=bwareaopen(tophatimg,20,8);
resultimg=region(tophatimg,[xf,yf],1,1.2);%区域生长
resultimg(find(resultimg>0.1))=1;
resultimg(find(resultimg~=1))=0;
resultimg=bwareaopen(resultimg,100,8);
imshow(resultimg)
title('分割结果')